services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  IchHabRecht\MaskExport\:
    resource: '../Classes/*'

  IchHabRecht\MaskExport\CodeGenerator\HtmlCodeGenerator:
    public: true
