services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  IchHabRecht\MaskExport\:
    resource: '../Classes/*'

  IchHabRecht\MaskExport\Command\ExportCommand:
    tags:
      - name: console.command
        command: 'mask:export'
        description: 'Export all mask elements'
